version: "3.1"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27019:27019

    volumes:
      - jeevanlink_mongo:/data/db

  redis-data:
    image: redis
    restart: unless-stopped
    ports:
      - 6380:6379
    volumes:
      - jeevanlink_redis/redis-data

  redis-session:
    image: redis
    restart: unless-stopped
    ports:
      - 6381:6379

volumes:
  jeevanlink_mongo:
  jeevanlink_redis:
