version: "3.1"

services:
  backend:
    build: .
    command: npm run start
    volumes:
      - .:/backend/
      - /backend/node_modules
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27020:27017
    volumes:
      - jeevanlink_mongo:/data/db

  redis:
    image: redis
    container_name: redis-session
    restart: unless-stopped
    ports:
      - 6381:6379

volumes:
  jeevanlink_mongo:
  jeevanlink_redis:
