# This is a basic workflow to help you get started with Actions

name: backend

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the backend branch
  push:
    branches: [main]
    paths:
      - "packages/backend/**"

  pull_request:
    branches: [main]
    paths:
      - "packages/backend/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./packages/backend/"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - run: npm ci
      - run: sudo docker-compose -f docker-compose-test.yml up -d
      - run: npm run build --if-present
      - run: npm test

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.6.0
        with:
          # Commit message
          commit_message: Passed tests, pushing latest changes.
          branch: main

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push backend to dokku
        uses: dokku/github-action@v1.0.1
        with:
          branch: main
          git_remote_url: "ssh://dokku@ente-dokku.jeevan.link/backendv1"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_push_flags: --force
